### PR TITLE
Added conditional for WebDriver in 'screenshotElement' method.

### PR DESCRIPTION
**Pull request by tairun**
Poor man's patch to make 'screenshotElement' method work with WebDriver helper.

### CODE REVIEW

**Comment by Kartikeya99** [comment]
Nice! This works!!

**Comment by puneet0191** [comment]
Thanks for testing and thanks for the patch @tairun :+1: will be available in the next release

**Comment by puneet0191** [comment]
@tairun can you please send PR to the upstream project?

**Review by puneet0191 — APPROVED** [review]

**Comment by tairun** [comment]
> @tairun can you please send PR to the upstream project?

Sorry for the delay. PR in upstream is available now.

Sidenote 1: Why did you fork the project if you are the one managing the original one?
Sidenote 2: Don't forget to bump the version number.

**Pull request merged**
